
const countyNames = {
  'Alameda':'Alameda', 
  'Alpine':'Alpine',
  'Amador':'Amador',
  'Butte':'Butte',
  'Calaveras':'Calaveras',
  'Colusa':'Colusa',
  'Contra Costa':'Contra Costa',
  'Del Norte':'Del Norte',
  'El Dorado':'El Dorado',
  'Fresno':'Fresno',
  'Glenn':'Glenn',
  'Humboldt':'Humboldt',
  'Imperial':'Imperial',
  'Inyo':'Inyo',
  'Kern':'Kern',
  'Kings':'Kings',
  'Lake':'Lake',
  'Lassen':'Lassen',
  'Los Angeles':'Los Angeles',
  'Madera':'Madera',
  'Marin':'Marin',
  'Mariposa' : 'Mariposa',
  'Mendocino' : 'Mendocino',
  'Merced' : 'Merced',
  'Modoc' : 'Modoc',
  'Mono' : 'Mono',
  'Monterey' : 'Monterey',
  'Napa' : 'Napa',
  'Nevada' : 'Nevada',
  'Orange' : 'Orange',
  'Placer' : 'Placer',
  'Plumas' : 'Plumas',
  'Riverside':'Riverside',
  'Sacramento':'Sacramento',
  'San Benito':'San Benito',
  'San Bernardino':'San Bernardino',
  'San Diego':'San Diego', 
  'San Francisco':'San Francisco', 
  'San Joaquin':'San Joaquin',
  'San Luis Obispo':'San Luis Obispo', 
  'San Mateo':'San Mateo', 
  'Santa Barbara':'Santa Barbara', 
  'Santa Clara':'Santa Clara',
  'Santa Cruz':'Santa Cruz',
  'Shasta':'Shasta', 
  'Sierra':'Sierra', 
  'Siskiyou':'Siskiyou', 
  'Solano':'Solano', 
  'Sonoma':'Sonoma',
  'Stanislaus':'Stanislaus', 
  'Sutter':'Sutter', 
  'Tehama':'Tehama', 
  'Trinity':'Trinity', 
  'Tulare':'Tulare', 
  'Tuolumne':'Tuolumn',
  'Ventura':'Ventura', 
  'Yolo':'Yolo', 
  'Yuba':'Yuba'
};

export default countyNames;
